session_name: cihai-unihan
start_directory: ./
before_script: ./bootstrap_env.py
windows:
- window-name: cihai-unihan
  layout: main-horizontal
  focus: true
  panes:
  - focus: true
  - pane
  - watching_testrunner --basepath ./ --pattern="*.py" 'python setup.py test'
  shell_command_before:
    - '[ -d .env -a -f .env/bin/activate ] && source .env/bin/activate'
  options:
    main-pane-height: 35
- window_name: docs
  layout: main-horizontal
  start_directory: doc/
  options:
    main-pane-height: 35
  shell_command_before: 
    - '[ -d ../.env -a -f ../.env/bin/activate ] && source ../.env/bin/activate'
  panes:
  - focus: true
  - pane
  - echo 'docs built to <http://0.0.0.0:8014/_build/html>'; python -m SimpleHTTPServer 8014
  - watching_testrunner --basepath ./ --pattern="*.rst" 'make html'
