language: python
python:
  - 2.6
  - 2.7
  - 3.3
matrix:
  allow_failures:
    - python: 2.6
before_install:
  - sudo apt-get update -qq
  - export PIP_USE_MIRRORS=true
  - pip install coveralls
  - pip install -e git+https://github.com/cihai/cihai-python.git#egg=cihai-python
install:
  - "pip install -e ."
script: coverage run --source=scripts setup.py test
after_success:
  - coveralls
